### PR TITLE
The installation file

### PR DESCRIPTION
**Pull request by brochuJP**
It is now easyer to install the vbaDeveloper project. You can follow the instruction that you see at the bigining of the file. We still have to install the libraries and change security level but the .xlam file is now created automaticaly.

### CODE REVIEW

**Comment by brochuJP** [comment]
There is also a way to automate installation the libraries but the VBA code need to refer to the path of the library. The problem is that the library is not always at the same place depending where you installed MS Office on your computer and what version is it (32 bit, 64 bit or 2010,2013, 2016). So I perfer to let the user select the library in the VB Editor.

**Comment by DecimalTurn** [comment]
Since Installer.bas is not supposed to be a module of vbaDeveloper.xlam, shouldn't it be located in the main repository (ie. with the README) ?

**Comment by brochuJP** [comment]
@DecimalTurn , I will let you have a look at it. I just updated branch accordingly.

**Comment by DecimalTurn** [comment]
@brochuJP I've made a pull request in your patch-1 branch to include some other changes. Let me know what you think.

**Comment by DecimalTurn** [comment]
@hilkoc Is there any additional things you'd like to be done before merging the pull request?

**Comment by hilkoc** [comment]
Thanks for your pull request. I hope to find the time to merge this in soon.

**Comment by hilkoc** [comment]
I've had a closer look at this installer and compared it with the steps in src/vbaDeveloper.xlam/Build.bas.

The Build.bas has 10 steps to complete the installation. Of those 10,  this installer takes care of step 1, 3, 6, 7.  That by itself is great, but the installer itself has an additional six steps to follow. All in all it doesn't make things any quicker. Actually it is more confusing, because now the installation steps are spread in two different files.

**Pull request closed without merging**
